server:
  port: 8081
  servlet:
    context-path: /api


spring:
  application:
    name: Springboot-backend
  ai:
    openai:
      api-key: sk-5792fabe875443af895e3a51e181031d
      base-url: https://api.deepseek.com
      options.model: 'deepseek-chat'
      options.temperature: 0.7

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aiagent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 170945

mybatis-plus:
  configuration:
    # mybatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


